### ISSUE TITLE
0.3.0 Plan

### ISSUE THREAD

**Issue by adashen** [adashen/vscode-tomcat#18]
- [x] Add start operation in context menu of tomcat explorer #9
- [x] Add Open in browser operation in context menu of tomcat explorer
- [x] Prompt user to restart when server.xml is change during running #8 
- [x] Solve Linux package issue #10 
- [x] Fix open web page button hidden in status bar issue. #7 
- [x] Fix tomcat still running after close #6
