### ISSUE TITLE
0.4.0 Plan

### ISSUE THREAD

**Issue by SummerSun** [adashen/vscode-tomcat#31]
- [x] Add command in server tree explorer for user to create a new server

- [x] Fix bug #37: show no command when there is no server in the server tree explorer

- [x] Show info message instead of error when this is no tomcat server to delete or stop #38 

- [x] Allow user to browser to create new tomcat server when there is no server to start

- [x] Proceed with info message instead of pop up error when user creates same tomcat server #32 

- [x] Categorize and better naming commands #29 

- [x] Browse file explorer directly for user to select tomcat server or war package without clicking browser
